export const USERS = [
  {
    userStatus: "активный",
    userId: "1",
    userDate: "Дата",
    userName: "Иванов Иван Иванович",
    userProgramm: "Продакт — менеджер для специалистов с опытом",
    userCountry: "Россия",
    userCity: "Москва",
    userTelegram: "@tgnickname",
    userPromocode: "samplepromocode13",
    userSendMerch: "Доступно: 2/2",
    userFeedback: "http://www.company.com",
    userHabr: "http://www.company.com",
    userCurator: "Анастасия Борисова",
    userMerch: "Позиция 1, Позиция 2",
    userHudiSize: "S",
    userSocksSize: "M",
    userIndex: "112233",
    userTotal: ' 1 200 000',
    userJanuare: '10 000',
    userFebruare: '10 000',
    userMart: '10 000',
    userApril: '10 000',
    userMay: '10 000',
    userJune: '10 000',
    userJuly: '10 000',
    userAugust: '10 000',
    userSeptember: '10 000',
    userOctober: '10 000',
    userNovember: '10 000',
    userDecember: '10 000',
    userMerchName: 'Толстовка',
    userMerchPrice: '2500',
    userHudi:'10',
    userCoffee:'10',
    userSticker:'10',
    userPlus:'10',
    userArzamas:'10',
    userShopper:'10',
    userBackpack:'10',
  },
  {
    userStatus: "уточняется",
    userId: "2",
    userDate: "Дата",
    userName: "Иванов Иван Иванович",
    userProgramm: "Продакт — менеджер для специалистов с опытом",
    userCountry: "Россия",
    userCity: "Москва",
    userTelegram: "@tgnickname",
    userPromocode: "samplepromocode13",
    userSendMerch: "Доступно: 2/2",
    userFeedback: "http://www.company.com",
    userHabr: "http://www.company.com",
    userCurator: "Анастасия Борисова",
    userMerch: "Позиция 1, Позиция 2",
    userHudiSize: "S",
    userSocksSize: "M",
    userIndex: "112233",
    userTotal: ' 1 200 000',
    userJanuare: '10 000',
    userFebruare: '10 000',
    userMart: '10 000',
    userApril: '10 000',
    userMay: '10 000',
    userJune: '10 000',
    userJuly: '10 000',
    userAugust: '10 000',
    userSeptember: '10 000',
    userOctober: '10 000',
    userNovember: '10 000',
    userDecember: '10 000',
    userMerchName: 'Толстовка',
    userMerchPrice: '2500',
    userHudi:'10',
    userCoffee:'10',
    userSticker:'10',
    userPlus:'10',
    userArzamas:'10',
    userShopper:'10',
    userBackpack:'10',
  },
  {
    userStatus: "на паузе",
    userId: "3",
    userDate: "Дата",
    userName: "Иванов Иван Иванович",
    userProgramm: "Продакт — менеджер для специалистов с опытом",
    userCountry: "Россия",
    userCity: "Москва",
    userTelegram: "@tgnickname",
    userPromocode: "samplepromocode13",
    userSendMerch: "Доступно: 2/2",
    userFeedback: "http://www.company.com",
    userHabr: "http://www.company.com",
    userCurator: "Анастасия Борисова",
    userMerch: "Позиция 1, Позиция 2",
    userHudiSize: "S",
    userSocksSize: "M",
    userIndex: "112233",
    userTotal: ' 1 200 000',
    userJanuare: '10 000',
    userFebruare: '10 000',
    userMart: '10 000',
    userApril: '10 000',
    userMay: '10 000',
    userJune: '10 000',
    userJuly: '10 000',
    userAugust: '10 000',
    userSeptember: '10 000',
    userOctober: '10 000',
    userNovember: '10 000',
    userDecember: '10 000',
    userMerchName: 'Толстовка',
    userMerchPrice: '2500',
    userHudi:'10',
    userCoffee:'10',
    userSticker:'10',
    userPlus:'10',
    userArzamas:'10',
    userShopper:'10',
    userBackpack:'10',
  },
  {
    userStatus: "не амбассадор",
    userId: "4",
    userDate: "Дата",
    userName: "Иванов Иван Иванович",
    userProgramm: "Продакт — менеджер для специалистов с опытом",
    userCountry: "Россия",
    userCity: "Москва",
    userTelegram: "@tgnickname",
    userPromocode: "samplepromocode13",
    userSendMerch: "Доступно: 2/2",
    userFeedback: "http://www.company.com",
    userHabr: "http://www.company.com",
    userCurator: "Анастасия Борисова",
    userMerch: "Позиция 1, Позиция 2",
    userHudiSize: "S",
    userSocksSize: "M",
    userIndex: "112233",
    userTotal: ' 1 200 000',
    userJanuare: '10 000',
    userFebruare: '10 000',
    userMart: '10 000',
    userApril: '10 000',
    userMay: '10 000',
    userJune: '10 000',
    userJuly: '10 000',
    userAugust: '10 000',
    userSeptember: '10 000',
    userOctober: '10 000',
    userNovember: '10 000',
    userDecember: '10 000',
    userMerchName: 'Толстовка',
    userMerchPrice: '2500',
    userHudi:'10',
    userCoffee:'10',
    userSticker:'10',
    userPlus:'10',
    userArzamas:'10',
    userShopper:'10',
    userBackpack:'10',
  },
];

export const PROMOCODES_DATA = [
  { label: "Статус", data: "userStatus" },
  { label: "ID", data: "userId" },
  { label: "Дата", data: "userDate" },
  { label: "ФИО", data: "userName" },
  { label: "Telegram", data: "userTelegram" },
  { label: "Промокод", data: "userPromocode" },
];

export const ambassadorsData = [
  { label: "Статус", data: "userStatus" },
  { label: "ID", data: "userId" },
  { label: "Дата", data: "userDate" },
  { label: "ФИО", data: "userName" },
  { label: "Программа", data: "userProgramm" },
  { label: "Страна", data: "userCountry" },
  { label: "Город", data: "userCity" },
];

export const CONTENT_DATA = [
  { label: "ID", data: "userId" },
  { label: "Отправка мерча", data: "userSendMerch" },
  { label: "Статус", data: "userStatus" },
  { label: "ФИО", data: "userName" },
  { label: "Telegram", data: "userTelegram" },
  { label: "Отзыв", data: "userFeedback" },
  { label: "Хабр", data: "userHabr" },
];

export const SEND_MERCH_DATA = [
  { label: "ID", data: "userId" },
  { label: "Куратор", data: "userCurator" },
  { label: "Мерч", data: "userMerch" },
  { label: "Размер толстовки", data: "userHudiSize" },
  { label: "Размер носков", data: "userSocksSize" },
  { label: "ФИО", data: "userName" },
  { label: "Индекс", data: "userIndex" },
];

export const BUDGET_DATA = [
  { label: "ID", data: "userId" },
  { label: "ФИО", data: "userName" },
  { label: "Итог", data: "userTotal" },
  { label: "Январь", data: "userJanuare" },
  { label: "Февраль", data: "userFebruare" },
  { label: "Март", data: "userMart" },
  { label: "Апрель", data: "userApril" },
  { label: "Май", data: "userMay" },
  { label: "Июнь", data: "userJune" },
  { label: "Июль", data: "userJuly" },
  { label: "Август", data: "userAugust" },
  { label: "Сентябрь", data: "userSeptember" },
  { label: "Октябрь", data: "userOctober" },
  { label: "Ноябрь", data: "userNovember" },
  { label: "Декабрь", data: "userDecember" },
];

export const BUDGET_PRICE = [
  { label: "ID", data: "userId" },
  { label: "Мерч", data: "userMerchName" },
  { label: "Стоимость", data: "userMerchPrice" },
];

export const LOYALTI_PROGRAMM_DATA = [
  { label: "ID", data: "userId" },
  { label: "ФИО", data: "userName" },
  { label: "Толстовка", data: "userHudi" },
  { label: "Кофе", data: "userCoffee" },
  { label: "Стикеры", data: "userSticker" },
  { label: "Плюс", data: "userPlus" },
  { label: "Арзамас", data: "userArzamas" },
  { label: "Шоппер", data: "userShopper" },
  { label: "Рюкзак", data: "userBackpack" },
];
